#!/usr/bin/env ruby
# frozen_string_literal: true

require "./lib/image_fetcher_organizer"
require "./lib/error_logger"

error_logger = ErrorLogger.new

ImageFetcherOrganizer.call(filenames: ARGV, error_logger: error_logger)
